spring:
    application:
        name: quora-app
    data:
        mongodb:
            host: localhost
            port: 27017
            database: quora_db
            auto-index-creation: true
            
